### ISSUE TITLE
[VMWare] Cannot Run Dynamic Engine due to exception

### ISSUE THREAD

**Issue by miguelfreitas93** [checkmarx-ts/CxDynEngine#21]
When trying to run Dynamic Engines for VMWare I got the following exception:
Is that possible to fix it ?
Thanks !

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.4.RELEASE)

2020-07-01 16:49:50.406  INFO 1 --- [           main] com.checkmarx.engine.app.Application     : Starting Application v1.3.2-SNAPSHOT on d8c1ba525cfe with PID 1 (/opt/cx-dyn.jar started by root in /opt)
2020-07-01 16:49:50.418  INFO 1 --- [           main] com.checkmarx.engine.app.Application     : No active profile set, falling back to default profiles: default
2020-07-01 16:49:53.261  INFO 1 --- [           main] ptablePropertiesBeanFactoryPostProcessor : Post-processing PropertySource instances
2020-07-01 16:49:53.365  INFO 1 --- [           main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource configurationProperties [org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertySource] to AOP Proxy
2020-07-01 16:49:53.367  INFO 1 --- [           main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource servletConfigInitParams [org.springframework.core.env.PropertySource$StubPropertySource] to EncryptablePropertySourceWrapper
2020-07-01 16:49:53.367  INFO 1 --- [           main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource servletContextInitParams [org.springframework.core.env.PropertySource$StubPropertySource] to 
EncryptablePropertySourceWrapper
2020-07-01 16:49:53.368  INFO 1 --- [           main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource systemProperties [org.springframework.core.env.PropertiesPropertySource] to EncryptableMapPropertySourceWrapper
2020-07-01 16:49:53.368  INFO 1 --- [           main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource systemEnvironment [org.springframework.boot.env.SystemEnvironmentPropertySourceEnvironmentPostProcessor$OriginAwareSystemEnvironmentPropertySource] to EncryptableMapPropertySourceWrapper
2020-07-01 16:49:53.369  INFO 1 --- [           main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource random [org.springframework.boot.env.RandomValuePropertySource] to EncryptablePropertySourceWrapper
2020-07-01 16:49:53.369  INFO 1 --- [           main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource applicationConfig: [file:./application.yml] [org.springframework.boot.env.OriginTrackedMapPropertySource] to EncryptableMapPropertySourceWrapper
2020-07-01 16:49:53.369  INFO 1 --- [           main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource applicationConfig: [classpath:/application.yml] [org.springframework.boot.env.OriginTrackedMapPropertySource] to EncryptableMapPropertySourceWrapper
2020-07-01 16:49:53.466  INFO 1 --- [           main] c.u.j.filter.DefaultLazyPropertyFilter   : Property Filter custom Bean not found with name 'encryptablePropertyFilter'. Initializing Default Property Filter
2020-07-01 16:49:53.527  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.retry.annotation.RetryConfiguration' of type [org.springframework.retry.annotation.RetryConfiguration$$EnhancerBySpringCGLIB$$33ca1211] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-07-01 16:49:54.360  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8585 (http)
2020-07-01 16:49:54.393  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-07-01 16:49:54.395  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.30]
2020-07-01 16:49:54.621  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-07-01 16:49:54.623  INFO 1 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 3252 ms
2020-07-01 16:49:55.071  INFO 1 --- [           main] c.u.j.r.DefaultLazyPropertyResolver      : Property Resolver custom Bean not found with name 'encryptablePropertyResolver'. Initializing Default Property Resolver2020-07-01 16:49:55.078  INFO 1 --- [           main] c.u.j.d.DefaultLazyPropertyDetector      : Property Detector custom Bean not found with name 'encryptablePropertyDetector'. Initializing Default Property Detector2020-07-01 16:49:55.281  INFO 1 --- [           main] c.c.engine.app.ApplicationConfig         : ctor()
2020-07-01 16:49:55.315  INFO 1 --- [           main] c.c.engine.spring.CoreApplicationConfig  : ctor()
2020-07-01 16:49:55.325  WARN 1 --- [           main] uration$JodaDateTimeJacksonConfiguration : Auto-configuration of Jackson's Joda-Time integration is deprecated in favor of using java.time (JSR-310).
2020-07-01 16:49:55.376  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cxEngineApiClient' defined in URL [jar:file:/opt/cx-dyn.jar!/BOOT-INF/lib/cx-dyn-engines-core-1.3.2-SNAPSHOT.jar!/com/checkmarx/engine/rest/CxEngineApiClient.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.checkmarx.engine.rest.Notification' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
2020-07-01 16:49:55.382  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2020-07-01 16:49:55.411  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-07-01 16:49:55.634 ERROR 1 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 2 of constructor in com.checkmarx.engine.rest.CxEngineApiClient required a bean of type 'com.checkmarx.engine.rest.Notification' that could not be found.

Action:

Consider defining a bean of type 'com.checkmarx.engine.rest.Notification' in your configuration.

**Comment by kmcdon83** [comment]
@miguelfreitas93 I have implemented the missing bean.  As discussed, we have not yet supported a VMware implementation.  Once this PR is approved/Merged, you should be able to get passed this particular issue.  @MithileshPawar will provide a review first thing tomorrow.

Can you make sure you provide the active profile while running (i.e --spring.profiles.active=vmware).

If there are still challenges, lets coordinate a working session and get access to the environment that we can work with.

**Comment by miguelfreitas93** [comment]
Got similar error, seems it was not fixed:

 docker run -it cxdyn:vmware-1.3.2
LOGBACK: No context given for c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1566723494

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.4.RELEASE)

2020-07-06 08:41:44.916  INFO 1 --- [           main] com.checkmarx.engine.app.Application     : Starting Application v1.3.2-SNAPSHOT on d1298687c5bc with PID 1 (/opt/cxdyn/cx-dyn.jar started by root in /opt/cxdyn)
2020-07-06 08:41:44.921  INFO 1 --- [           main] com.checkmarx.engine.app.Application     : No active profile set, falling back to default profiles: default
2020-07-06 08:41:46.863  INFO 1 --- [           main] ptablePropertiesBeanFactoryPostProcessor : Post-processing PropertySource instances
2020-07-06 08:41:46.980  INFO 1 --- [           main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource configurationProperties [org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertySource] to AOP Proxy
2020-07-06 08:41:46.982  INFO 1 --- [           main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource servletConfigInitParams [org.springframework.core.env.PropertySource$StubPropertySource] to EncryptablePropertySourceWrapper
2020-07-06 08:41:46.982  INFO 1 --- [           main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource servletContextInitParams [org.springframework.core.env.PropertySource$StubPropertySource] to EncryptablePropertySourceWrapper
2020-07-06 08:41:46.982  INFO 1 --- [           main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource systemProperties [org.springframework.core.env.PropertiesPropertySource] to EncryptableMapPropertySourceWrapper     
2020-07-06 08:41:46.982  INFO 1 --- [           main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource systemEnvironment [org.springframework.boot.env.SystemEnvironmentPropertySourceEnvironmentPostProcessor$OriginAwareSystemEnvironmentPropertySource] to EncryptableMapPropertySourceWrapper
2020-07-06 08:41:46.982  INFO 1 --- [           main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource random [org.springframework.boot.env.RandomValuePropertySource] to EncryptablePropertySourceWrapper
2020-07-06 08:41:46.982  INFO 1 --- [           main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource applicationConfig: [classpath:/application.yml] [org.springframework.boot.env.OriginTrackedMapPropertySource] to EncryptableMapPropertySourceWrapper
2020-07-06 08:41:47.076  INFO 1 --- [           main] c.u.j.filter.DefaultLazyPropertyFilter   : Property Filter custom Bean not found with name 'encryptablePropertyFilter'. Initializing Default Property Filter
2020-07-06 08:41:47.139  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.retry.annotation.RetryConfiguration' of type [org.springframework.retry.annotation.RetryConfiguration$$EnhancerBySpringCGLIB$$6b4e61c3] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-07-06 08:41:47.830  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8585 (http)
2020-07-06 08:41:47.854  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-07-06 08:41:47.856  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.30]
2020-07-06 08:41:47.985  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-07-06 08:41:47.987  INFO 1 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 2358 ms
2020-07-06 08:41:48.238  INFO 1 --- [           main] c.u.j.r.DefaultLazyPropertyResolver      : Property Resolver custom Bean not found with name 'encryptablePropertyResolver'. Initializing Default Property Resolver
2020-07-06 08:41:48.247  INFO 1 --- [           main] c.u.j.d.DefaultLazyPropertyDetector      : Property Detector custom Bean not found with name 'encryptablePropertyDetector'. Initializing Default Property Detector
2020-07-06 08:41:48.471  INFO 1 --- [           main] c.c.engine.app.ApplicationConfig         : ctor()
2020-07-06 08:41:48.554  INFO 1 --- [           main] c.c.engine.spring.CoreApplicationConfig  : ctor()
2020-07-06 08:41:48.570  WARN 1 --- [           main] uration$JodaDateTimeJacksonConfiguration : Auto-configuration of Jackson's Joda-Time integration is deprecated in favor of using java.time (JSR-310).
2020-07-06 08:41:48.645  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'engineService' defined in URL [jar:file:/opt/cxdyn/cx-dyn.jar!/BOOT-INF/lib/cx-dyn-engines-core-1.3.2-SNAPSHOT.jar!/com/checkmarx/engine/servers/EngineService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cxEngineApiClient' defined in URL [jar:file:/opt/cxdyn/cx-dyn.jar!/BOOT-INF/lib/cx-dyn-engines-core-1.3.2-SNAPSHOT.jar!/com/checkmarx/engine/rest/CxEngineApiClient.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.checkmarx.engine.rest.Notification' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
2020-07-06 08:41:48.657  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2020-07-06 08:41:48.699  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-07-06 08:41:48.929 ERROR 1 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   :

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 2 of constructor in com.checkmarx.engine.rest.CxEngineApiClient required a bean of type 'com.checkmarx.engine.rest.Notification' that could not be found.


Action:

Consider defining a bean of type 'com.checkmarx.engine.rest.Notification' in your configuration.

**Comment by miguelfreitas93** [comment]
Here my Dockerfile:
FROM openjdk:8-jdk-alpine

ARG VERSION
ARG VIRTUALIZATION

RUN echo ${VERSION} && \
    echo ${VIRTUALIZATION}

WORKDIR /opt/cxdyn

RUN wget https://github.com/checkmarx-ts/CxDynEngine/releases/download/${VERSION}/cx-dyn-engines-app-${VIRTUALIZATION}-${VERSION}-SNAPSHOT.jar -O cx-dyn.jar && \
    ls -la

ENTRYPOINT ["/usr/bin/java"]

CMD ["-Xms512m", "-Xmx1024m","-Djava.security.egd=file:/dev/./urandom", "-jar", "/opt/cxdyn/cx-dyn.jar"]

EXPOSE 8080:8080

Here my Docker-compose:
version: '3'

services:
    cxdyn:
        image: cxdyn:vmware-${VERSION}
        container_name: cxdyn-vmware-${VERSION}
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                VERSION: ${VERSION}
                VIRTUALIZATION: ${VIRTUALIZATION}

Here my .env file:
VERSION=1.3.2
VIRTUALIZATION=VMWARE

**Comment by kmcdon83** [comment]
@miguelfreitas93  as mentioned, please ensure the vmware profile is specified on cli.  For reference I have the following used to launch:
```java -jar cx-dyn-engines-app-VMWARE-1.3.2-SNAPSHOT.jar --spring.profiles.active=vmware --spring.config.location=./application-vmware.yml```

Can you update your CMD to include the profile?

You will also need a custom yaml and you can see my sample command references the exact location (example below).  My environment fails due to the fact I do not have an instance of VMWare to work with and fails when connecting to the SDK.
```
server:
  port: 8585 #Port for webserver to run (/health endpoint can be used to monitor service is up)

logging:
  file: cx-engines.log
  level:
    com:
      checkmarx:
        engine: info
    org:
      apache:
        http: info
      org:
        springframework: info

cx:
  cxEngineUseSSL: true #Use http/https to monitor and register Engines with
  concurrentScanLimit: 3 #Max number of concurrent scans (Engines) that DE will manage
  cxEnginePrefix: '**' #Prefix used within Registering engine in CX UI
  expireEngineBufferMins: 1 #Grace period before expiring and engine
  idleMonitorSecs: 30 #How often to check idle engines to determine if expired (ready for termination)
  queueCapacity: 100
  queueIntervalSecs: 15
  queueingEngineName: DynamicEngine #Name given to the Blocked Engine in Cx UI
  restUrl: https://<CXINSANCE>
  timeoutSecs: 120 #HTTP client request timeout (connection and read)
  terminateOnStop: false
  userName: XXXXXX #Checkmarx user (must have access to register engines)
  password: XXXXXX #Checkmarx password
  notificationId: #ARN for notification - empty when not using AWS


cx-engine:
  engineExpireIntervalSecs: 3600 #Blocks of time an instance is paid by - this is used for expiring/termination of instances
  enginePrefix: cx-engine #Prefix given to naming the instance within the cloud provider
  pool:
    - count: 3 # Maximum number of instances that can be launched for this pool size
      minimum: 1 # Minimum number of instances to leave running at all times.  These will be launched on startup, if not already running.
      scanSize: # Name and LOC range for the above pool
        name: S # Name of this engine pool/size
        minLOC: 0
        maxLOC: 250000
    - count: 3
      minimum: 0
      scanSize:
        name: M
        minLOC: 250001
        maxLOC: 1000000
    - count: 1
      minimum: 0
      scanSize:
        name: L
        minLOC: 1000001
        maxLOC: 999999999

cx-vmware-engine:
  username: XXXXXX
  password: XXXXXX
  url-str: https://IPADDRESS/sdk
  bypassSSLVerification: true
  datacenter-name: DatacenterName
  templateVMName: TemplateVM
  engineSizeMap:
    S: small
    M: medium
    L: large
  engineMemSizeMap:
    S: 8192
    M: 16384
    L: 32768
  engineCpuSizeMap:
      S: 4
      M: 6
      L: 8
  usePublicUrlForCx: false #Cx will register the Engine with Public or Private IP
  usePublicUrlForMonitor: false #DE will monitor if an Engine is up and running based on Public or Private IP        
```

**Comment by miguelfreitas93** [comment]
@kmcdon83 I forgot about that, thanks ! 
Can you please add those details "--spring.profiles.active=vmware --spring.config.location=./application-vmware.yml" to all Dockerfiles ?

**Comment by kmcdon83** [comment]
#23 has been created.
